### ISSUE TITLE
fizzbuzz 구현

### ISSUE THREAD

**Issue by ChrisSeofinance** [ChrisSeofinance/fizzbuzzforme#1]
## 목표
나혼자 완성하는 피즈버즈

## 요구사항

-범위 1~20까지 정수

## task
- [] print fizz if is times of 3
- [] print buzz if is times of 5
- [] print fizz buzz if is times of 15
- [] print itself for any other case

## References

- https://en.wikipedia.org/wiki/Fizz_buzz
