### ISSUE TITLE
fizzbuzz 구현

### ISSUE THREAD

**Issue by ChrisSeofinance** [ChrisSeofinance/fizzbuzzforme#3]
##설명
if 와 for 문을 활용하여 피즈버즈를 구현하였습니다.

## Tasks

- [ ] Print 'fizz' if i is times of 3.
- [ ] Print 'buzz' if i is times of 5.
- [ ] Print 'fizzbuzz' if i is times of 15.
- [ ] Print i itself for any other cases.
